### ISSUE TITLE
Suggestion: Scaling of buttons / text is too big on some pages

### ISSUE THREAD

**Issue by moritz1000** [hinto-janai/festival#31]
## Feature
I am unsure whether this is a bug or intended functionality, but personally, I believe that certain elements scale excessively with certain window sizes.

## Screenshots
![image](https://github.com/hinto-janai/festival/assets/35174351/02afe840-2ec1-4c65-91fa-8e9a187cb03a)

For instance, on the settings page:

- The Reset & Save buttons appear excessively large.
- The same applies to the headings e.g.: "Collection" and "Artist Sort Order," along with their descriptions.

In my opinion, this results in excessive wasted space and leads to a poor user experience, as users must scroll extensively to access each setting. Consequently, the settings menu becomes confusing, whereas it should be possible to display at least twice the amount of settings within the same space.

___

I believe these scaling inconsistencies are prevalent throughout Festival, although they vary in severity from one element to another. 

However, I do appreciate the design language and implemented ideas in Festival overall. My concern is solely focused on the scaling & size aspect.

**Comment by hinto-janai** [comment]
Scaling that works for everybody is hard to get right because of:
- OS (Windows/macOS/Linux all have different scaling)
- Custom user OS-wide scaling (100%, 200%)
- Desktop environment (Title bars take up varying amount of space)
- User screen resolution

If you make Festival's default scale good on one combination, it'll look bad on the rest, so I chose the middle ground that works on most major ones, specifically:
- Windows 10/11, default scaling, 1080p+
- macOS, default scaling, 1080p+
- Linux, GNOME, default scaling, 1080p+

Although now, in [`v1.0.1`](https://github.com/hinto-janai/festival/releases/tag/v1.0.1) there's a `Pixels Per Point` setting that allows you to scale Festival manually to scale correctly for any setup.

> For instance, on the settings page

Yes, they're big. I prefer a scroll of settings instead of everything tiny in one screen. Although maybe the real reason it's that way is actually because doing that type of layout in `egui` is a nightmare when you mix in justification, scaling, etc.

**Comment by hinto-janai** [comment]
P.S. the screenshot does have bigger UI than intended. You could lower the `Pixels Per Point` setting.
