### ISSUE TITLE
Huge memory footprint

### ISSUE THREAD

**Issue by LukeZBaker** [hinto-janai/festival#60]
## OS & Version
Festival v1.2.0
Linux x64
Collection v2
Audio v0
State v1
Settings v2

## Bug
Huge memory footprint 

## Steps
Run ps_mem utility with festival and a medium size collection of albums

ps_mem reports that Festival uses a massive amount of RAM (compared to all other music players). With a 290CD album collection, ps_mem reports RAM for the festival process is over 900MB

Private      +   Shared   =  RAM used      Program
901.9 MiB +  10.5 MiB = 912.3 MiB       festival

**Comment by necromeo** [comment]
Hadn't really thought of checking out how much memory Festival consume. Turns out, in my case, with a ~1300 album collections it's around 1.1GB. Which is way too much!

**Comment by hinto-janai** [comment]
Most of the memory usage is from album art.

All album art (500x500 versions) is held in memory so that there is no loading. Other music players that do this (e.g Lollypop) will use similar amounts of memory (although Lollypop uses 300x300).

I agree it's a lot of memory usage but it's not a bug, the images have to be in memory unless slowly (de)allocating images each time they (dis)appear and using CPU time is seen as a better tradeoff, like MusicBee does.

**Comment by LukeZBaker** [comment]
OK, maybe not a bug, but certainly a design flaw.

 I've reviewed dozens of open source music players, and yours has the biggest memory footprint (even larger than bloated Electron-based players). All because you are wasting huge amounts of memory permanently caching album covers.
